//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoffCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Pay = new HashSet<Pay>();
            this.Request = new HashSet<Request>();
        }
    
        public int ClientID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Patron { get; set; }
        public string Phone { get; set; }
        public string AbonentNumb { get; set; }
        public int AdressID { get; set; }
        public decimal Balance { get; set; }
        public int TarifID { get; set; }
        public bool IsDelected { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Tarif Tarif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay> Pay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
