//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoffCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employ()
        {
            this.Pay = new HashSet<Pay>();
        }
    
        public int EmployID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Patron { get; set; }
        public string PassportNum { get; set; }
        public string PasspportSer { get; set; }
        public int PostID { get; set; }
        public bool IsDeleted { get; set; }
        public string LoginUser { get; set; }
        public string PasswordUser { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay> Pay { get; set; }
    }
}
