//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoffCursach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TutoffCourseEntities : DbContext
    {
        public TutoffCourseEntities()
            : base("name=TutoffCourseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ElemReq> ElemReq { get; set; }
        public virtual DbSet<Employ> Employ { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StatusReq> StatusReq { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarif> Tarif { get; set; }
        public virtual DbSet<TypeReq> TypeReq { get; set; }
        public virtual DbSet<TypeStaff> TypeStaff { get; set; }
    }
}
