//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoffCursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public string Title { get; set; }
        public string TextFull { get; set; }
        public int ClientID { get; set; }
        public int ElemReqID { get; set; }
        public System.DateTime DateReq { get; set; }
        public int StatusReqID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ElemReq ElemReq { get; set; }
        public virtual StatusReq StatusReq { get; set; }
    }
}
